# Generated by Django 6.0.3 on 2026-04-04 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Loja')),
                ('slug', models.SlugField(help_text='Como vai ficar no link ex: /minha-loja', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Loja')),
                ('cor_principal', models.CharField(default='#b08d57', help_text='Cor HEX. Ex: #b08d57 (Dourado)', max_length=7)),
                ('tema_escolhido', models.CharField(choices=[('Elegante', 'Elegante (Light com Dourado)'), ('Moderno', 'Moderno (Cores Vivas)'), ('Dark', 'Dark (Fundo Escuro)')], default='Elegante', max_length=20)),
                ('whatsapp_numero', models.CharField(help_text='Ex: 5511999999999', max_length=20, verbose_name='Número de WhatsApp')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.loja'),
        ),
    ]
