# Generated by Django 6.0.3 on 2026-04-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_loja_produto_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave PIX se for PIX Manual', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='gateway_provider',
            field=models.CharField(blank=True, help_text='MP, ASAAS, EFI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='gateway_token',
            field=models.CharField(blank=True, help_text='Token/Secret do Gateway ou URL Externo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='n8n_webhook_url',
            field=models.URLField(blank=True, help_text='URL do n8n para onde o SaaS enviará os eventos', null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='tipo_pagamento',
            field=models.CharField(choices=[('PIX_MANUAL', 'Pix Manual (QR Code s/ Automação)'), ('GATEWAY', 'Gateway Integrado (Mercado Pago, Efí)'), ('EXTERNO', 'Checkout Externo (Hotmart, Eduzz)'), ('LINK', 'Link de Pagamento Simples')], default='PIX_MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='webhook_token',
            field=models.CharField(blank=True, help_text='Auth Token de segurança do Webhook', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=25)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('id_transacao_gateway', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='produtos.loja')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.pedido')),
            ],
        ),
    ]
