# Generated by Django 6.0.3 on 2026-04-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_loja_chave_pix_loja_gateway_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp para expiração do bloqueio de estoque', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20),
        ),
    ]
