# Generated by Django 6.0.3 on 2026-04-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_pedido_expira_em_alter_pedido_status_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='banner_topo',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner de Destaque'),
        ),
        migrations.AddField(
            model_name='loja',
            name='subtitulo_loja',
            field=models.CharField(blank=True, help_text='Frase que aparece abaixo do nome/logo', max_length=255, null=True, verbose_name='Bio/Subtítulo'),
        ),
    ]
