# Generated by Django 6.0.3 on 2026-04-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_loja_banner_topo_loja_subtitulo_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='bi-tag', help_text='Nome do ícone Bootstrap Icons. Ex: bi-handbag', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='produtos.loja')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria'),
        ),
    ]
