# Generated by Django 6.0.3 on 2026-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem (Estilo Story)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='mostrar_estilo_story',
            field=models.BooleanField(default=True, help_text='Se deve aparecer no menu de círculos'),
        ),
    ]
