# Generated by Django 6.0.3 on 2026-04-04 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_categoria_imagem_categoria_mostrar_estilo_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook (URL)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram (URL)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to=settings.AUTH_USER_MODEL),
        ),
    ]
