# Generated by Django 6.0.3 on 2026-04-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_loja_facebook_url_loja_instagram_url_loja_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Deve corresponder ao nome do arquivo em templates/vitrines/', unique=True)),
                ('layout_padrao', models.CharField(choices=[('grid', 'Grid'), ('lista', 'Lista')], default='grid', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='plano',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('master', 'Master')], default='basic', max_length=20),
        ),
        migrations.CreateModel(
            name='TemaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_primaria', models.CharField(default='#000000', max_length=7)),
                ('cor_secundaria', models.CharField(default='#ffffff', max_length=7)),
                ('mostrar_banner', models.BooleanField(default=True)),
                ('mostrar_stories', models.BooleanField(default=True)),
                ('qtd_produtos_home', models.IntegerField(default=6)),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('lista', 'Lista')], default='grid', max_length=20)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tema', to='produtos.loja')),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.template'),
        ),
    ]
