# Generated by Django 6.0.3 on 2026-04-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_template_loja_plano_temaloja_loja_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='temaloja',
            name='alinhamento_logo',
            field=models.CharField(choices=[('esquerda', 'Esquerda'), ('centro', 'Centro')], default='esquerda', max_length=20),
        ),
        migrations.AddField(
            model_name='temaloja',
            name='fonte_familia',
            field=models.CharField(choices=[('sans', 'Moderna (Sans-Serif)'), ('serif', 'Clássica (Serif)'), ('modern', 'Estilizada (Modern)')], default='sans', max_length=20),
        ),
    ]
