# Generated by Django 6.0.3 on 2026-08-11
from django.db import migrations

def migrate_lojas_to_accounts(apps, schema_editor):
    Plan = apps.get_model('produtos', 'Plan')
    Account = apps.get_model('produtos', 'Account')
    Subscription = apps.get_model('produtos', 'Subscription')
    AccountUser = apps.get_model('produtos', 'AccountUser')
    Loja = apps.get_model('produtos', 'Loja')

    # Defaults de Planos
    plan_data = {
        'basic': {'max_lojas': 1, 'max_produtos_por_loja': 10, 'max_usuarios': 1, 'preco_mensal': 0},
        'pro': {'max_lojas': 3, 'max_produtos_por_loja': 50, 'max_usuarios': 5, 'preco_mensal': 49.90},
        'master': {'max_lojas': 10, 'max_produtos_por_loja': 999, 'max_usuarios': 20, 'preco_mensal': 199.90},
    }
    
    plans = {}
    for nome, defaults in plan_data.items():
        plan, _ = Plan.objects.get_or_create(nome=nome, defaults=defaults)
        plans[nome] = plan

    PLAN_HIERARCHY = {'master': 3, 'pro': 2, 'basic': 1}

    # Lojas agrupadas por owner
    lojas_sem_account = Loja.objects.filter(account__isnull=True)
    
    owners_lojas = {}
    lojas_sem_owner = []

    for loja in lojas_sem_account:
        if loja.owner_id:
            owners_lojas.setdefault(loja.owner_id, []).append(loja)
        else:
            lojas_sem_owner.append(loja)

    # Processar por owner
    for owner_id, lojas_list in owners_lojas.items():
        highest_plan_name = 'basic'
        highest_score = 0
        for l in lojas_list:
            plano_antigo = getattr(l, 'plano', 'basic') or 'basic'
            score = PLAN_HIERARCHY.get(plano_antigo, 1)
            if score > highest_score:
                highest_score = score
                highest_plan_name = plano_antigo

        selected_plan = plans.get(highest_plan_name, plans['basic'])
        first_loja = lojas_list[0]
        
        account_nome = getattr(first_loja.owner, 'username', first_loja.nome)
        account = Account.objects.create(nome=account_nome)
        
        # Criar AccountUser
        AccountUser.objects.get_or_create(
            account=account,
            user=first_loja.owner,
            defaults={'role': 'owner', 'status': 'active'}
        )
        
        # Criar Subscription
        Subscription.objects.create(account=account, plan=selected_plan, status='active')

        # Vincular todas as lojas do owner a esta account
        for l in lojas_list:
            l.account = account
            l.save(update_fields=['account'])

    # Processar lojas sem owner
    for l in lojas_sem_owner:
        plano_antigo = getattr(l, 'plano', 'basic') or 'basic'
        selected_plan = plans.get(plano_antigo, plans['basic'])
        account = Account.objects.create(nome=l.nome)
        Subscription.objects.create(account=account, plan=selected_plan, status='active')
        l.account = account
        l.save(update_fields=['account'])

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_plan_account_subscription_accountuser_loja_account'),
    ]

    operations = [
        migrations.RunPython(migrate_lojas_to_accounts, reverse_migration),
    ]
