# Generated by Django 6.0.3 on 2026-08-11
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_data_migrate_loja_to_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='plano',
        ),
        migrations.AlterField(
            model_name='loja',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='produtos.account'),
        ),
    ]
